spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: parent
          uri: http://localhost:8081
          predicates:
            - Path=/parent/**

        - id: child
          uri: http://localhost:8082
          predicates:
            - Path=/child/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8080


